# app-with-argocd-service-01.yaml
apiVersion: v1
kind: Service
metadata:
  name: app-with-argocd-service
  namespace: app-with-argocd
spec:
  selector:
    app.kubernetes.io/name: app-with-argocd
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 31002
      port: 8080
      targetPort: 8080
