apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: app-with-argocd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-with-argocd
    spec:
      containers:
        - name: app-with-argocd
          image: amberlee0201/app-with-argocd:9bc3f84b4fdd8d37cd523993ef3a39c2f96f409a
