# db-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: app-with-argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql
    spec:
      containers:
        - name: mysql-container
          image: mysql
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: app12345
            - name: MYSQL_DATABASE
              value: app
            - name: MYSQL_USER
              value: app
            - name: MYSQL_PASSWORD
              value: app12345
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysqldata
      volumes:
        - name: mysqldata
          persistentVolumeClaim:
            claimName: db-pvc
