# db-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: app-with-argocd
  labels:
    app.kubernetes.io/name: mysql
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 31306
  selector:
    app.kubernetes.io/name: mysql
